# Generated by Django 3.0.8 on 2020-09-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0003_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
