# Generated by Django 3.0.8 on 2020-09-09 02:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200831_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 2, 42, 21, 842058, tzinfo=utc)),
        ),
    ]
