# Generated by Django 3.0.8 on 2020-09-13 00:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200912_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 0, 4, 34, 830341, tzinfo=utc)),
        ),
    ]
