# Generated by Django 3.0.8 on 2021-02-07 02:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200912_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 2, 37, 1, 702392, tzinfo=utc)),
        ),
    ]
