# Generated by Django 3.0.8 on 2021-02-17 23:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210206_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 23, 27, 5, 867608, tzinfo=utc)),
        ),
    ]
