# Generated by Django 3.0.8 on 2021-02-19 00:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20210217_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 0, 45, 27, 962936, tzinfo=utc)),
        ),
    ]
