# Generated by Django 3.0.8 on 2021-02-20 02:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20210219_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 2, 41, 58, 517329, tzinfo=utc)),
        ),
    ]
