# Generated by Django 3.0.8 on 2021-02-20 05:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20210219_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 5, 18, 48, 995779, tzinfo=utc)),
        ),
    ]
