# Generated by Django 3.0.8 on 2021-06-25 01:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20210219_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 1, 45, 45, 61953, tzinfo=utc)),
        ),
    ]
