# Generated by Django 3.0.8 on 2021-02-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_auto_20210219_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabulardatasets',
            name='dataset_name',
            field=models.TextField(unique=True),
        ),
    ]
