# Generated by Django 3.0.8 on 2021-02-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_auto_20210219_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycsvrow',
            name='row_values',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mycsvrow',
            name='row_variables',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
